- name: Provision
  hosts: workbox
  roles:
    - role: nickjj.user
      become: yes
    # install pip in pyenv
    # - role: geerlingguy.pip
    - role: geerlingguy.docker
      become: yes
    - role: geerlingguy.java
      become: yes
    - role: viasite-ansible.zsh
      become: yes