- name: Provision
  hosts: workbox
  roles:
    - role: nickjj.user
    - role: geerlingguy.pip
    - role: geerlingguy.docker
      become: yes
    - role: geerlingguy.java
      become: yes
    - { role: viasite-ansible.zsh }
    - role: ferrarimarco.xfce
