- name: Provision
  hosts: workspace
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
      become: yes
    - role: geerlingguy.java
      become: yes
    - role: viasite-ansible.zsh
