---

- hosts: pi
  roles:

  tasks:
    - name: Mount external HDD
      mount:
        path: /srv
        src: "{{ hdd }}"
        fstype: ext4
        opts: noatime,noexec,nosuid
        state: mounted
      when: hdd is defined

    - name: External HDD is owned by pi
      file:
        path: /srv
        state: directory
        recurse: true
        owner: pi
      when: hdd is defined

    - name: Install packages
      apt:
        name: "{{ packages }}"
        state: present

    # - name: Uninstall watchdog daemon
    #   apt:
    #     name: watchdog
    #     state: absent
    #   tags: watchdog

    # - name: Configure systemd watchdog
    #   lineinfile:
    #     path: /etc/systemd/system.conf
    #     regexp: "#?RuntimeWatchdogSec"
    #     line: "RuntimeWatchdogSec=20"
    #   tags: watchdog

- hosts: pi
  roles:
    - { role: jnv.unattended-upgrades, tags: unattended_upgrades }