all:
  vars:
    ansible_user:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # ansible_python_interpreter: /usr/bin/python

    # geerlingguy.docker
    pip_install_packages: [docker-py]
    docker_users: []
    # docker_compose_version: ""
    docker_compose_path: /usr/bin/docker-compose
    docker_install_compose: True

    # viasite-ansible.zshs
    zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - ssh-agent
    zsh_autosuggestions_bind_key: "^U"
  children:
    playground:
      hosts:
        deb9p:
          ansible_host: 192.168.56.101 # host where ansible docker container is running
    workspace:
      hosts:
        deb10w:
          ansible_host: 192.168.56.102 # host where ansible docker container is running
