all:
  vars:
    # ansible_user:
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # ansible_python_interpreter: /usr/bin/python

    # geerlingguy.docker
    # docker_package_state: latest
    pip_install_packages: [docker-py]
    docker_users: [acherlyonok]
    # docker_compose_version: ""
    docker_compose_path: /usr/local/bin/docker-compose
    docker_install_compose: True
    # viasite-ansible.zshs
    zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - ssh-agent
      - git
    zsh_autosuggestions_bind_key: "^U"
  children:
    playground:
      hosts:
        deb9p:
          ansible_host: 192.168.56.101 # host where ansible docker container is running or external host
    workbox:
      hosts:
        deb10w:
          ansible_user: acherlyonok
          ansible_host: 10.0.2.15
          user_name: acherlyonok # nickjj.user
          user_local_ssh_key_path: "files/acherlyonok@gmail.com.pub"
          zsh_user: acherlyonok # viasite-ansible.zsh
          # ferrarimarco_xfce_desktop_manager_user: acherlyonok # ferrarimarco.xfce
          ansible_ssh_private_key_file: "~/.ssh/acherlyonok@gmail.com.pem"
    rpi:
      hosts:
        rpi1:
          ansible_user: rpi
          ansible_host: rpi1
          # user_name: acherlyonok # nickjj.user
          # user_local_ssh_key_path: "files/acherlyonok@gmail.com.pub"
          # zsh_user: acherlyonok # viasite-ansible.zsh
          # ferrarimarco_xfce_desktop_manager_user: acherlyonok # ferrarimarco.xfce
          ansible_ssh_private_key_file: "~/.ssh/acherlyonok@gmail.com.pem"
          ansible_become: True
          packages:
            - p7zip-full
            - rpi-eeprom
          unattended_upgrades__auto_reboot: True
          transmission_download_dir: /srv/downloads
          transmission_rpc_whitelist: "192.168.0.*"
          transmission_user: "{{ ansible_user }}"
          transmission_watch_dir: /srv/torrents
          tmux_users:
            - pi
          samba_users:
            - name: "{{ ansible_user }}"
              password: "{{ ansible_ssh_pass }}"
          samba_config_file: smb.conf

          hifiberry_enabled: False
