all:
  vars:
    # ansible_user:
    # ansible_ssh_private_key_file: ~/.ssh/id_rsa
    # ansible_python_interpreter: /usr/bin/python

    # geerlingguy.docker
    # docker_package_state: latest
    pip_install_packages: [docker-py]
    docker_users: [acherlyonok]
    # docker_compose_version: ""
    docker_compose_path: /usr/local/bin/docker-compose
    docker_install_compose: True
    # viasite-ansible.zshs
    zsh_antigen_theme: "romkatv/powerlevel10k powerlevel10k"
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
      - ssh-agent
      - git
    zsh_autosuggestions_bind_key: "^U"
  children:
    playground:
      hosts:
        deb9p:
          ansible_host: 192.168.56.101 # host where ansible docker container is running
    workbox:
      hosts:
        deb10w:
          ansible_host: 192.168.56.101 # host where ansible docker container is running
          user_name: acherlyonok # nickjj.user
          user_local_ssh_key_path: "../../files/acherlyonok@gmail.com.pub"
          zsh_user: acherlyonok # viasite-ansible.zsh
          ferrarimarco_xfce_desktop_manager_user: acherlyonok # ferrarimarco.xfce
